export const MODULE_SHORTCUTS = {
  analytics: [
    'Analyze F&B market in Saudi Arabia',
    'Consumer spending trends in beverages',
    'Market size for healthy snacks',
    'Growth forecast for organic food',
    'Competitive landscape analysis',
    'Price sensitivity in premium products',
  ],
  research: [
    'What triggers juice purchases in Saudi Arabia?',
    'Analyze eating habits in Ramadan',
    'Shopping behavior in Saudi supermarkets',
    'Latest F&B trends in Saudi Arabia',
    'Consumer attitudes toward organic food',
    'Brand loyalty patterns in F&B',
  ],
  campaigns: [
    'Generate Ramadan campaign strategy',
    'Product launch campaign plan',
    'Seasonal promotion strategy',
    'Brand awareness campaign',
    'Social media campaign ideas',
    'Influencer marketing strategy',
  ],
  'focus-groups': [
    'Run focus group for new beverage',
    'Test packaging design feedback',
    'Brand perception study',
    'Product taste testing protocol',
    'Price point sensitivity research',
    'Target audience segmentation',
  ],
  channels: [
    'Optimize social media strategy',
    'Retail distribution analysis',
    'E-commerce channel strategy',
    'Traditional media effectiveness',
    'Influencer channel optimization',
    'Omnichannel integration plan',
  ],
  trends: [
    'Latest F&B trends in Saudi Arabia',
    'Emerging health food trends',
    'Growing food categories in 2025',
    'Declining beverage segments',
    'Consumer behavior shifts',
    'Technology trends in F&B',
  ],
  brand: [
    'Brand positioning strategy',
    'Competitive brand analysis',
    'Brand messaging framework',
    'Brand identity development',
    'Brand equity measurement',
    'Brand extension opportunities',
  ],
  insights: [
    'Deep consumer insights for beverages',
    'Purchase motivation analysis',
    'Barriers to product adoption',
    'Consumer decision journey',
    'Emotional drivers of choice',
    'Cultural influences on consumption',
  ],
  strategy: [
    'Go-to-market strategy',
    'Growth strategy roadmap',
    'Competitive strategy framework',
    'Market entry strategy',
    'Product portfolio strategy',
    'Digital transformation strategy',
  ],
};

